/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCreateAccountRouteImport } from './routes/auth/create-account'
import { Route as AuthenticatedAuthOnboardingRouteImport } from './routes/_authenticated/auth/onboarding'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateAccountRoute = AuthCreateAccountRouteImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthOnboardingRoute =
  AuthenticatedAuthOnboardingRouteImport.update({
    id: '/auth/onboarding',
    path: '/auth/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/verify-email'
    | '/auth/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/verify-email'
    | '/auth/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/verify-email'
    | '/_authenticated/auth/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/auth/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auth/onboarding': {
      id: '/_authenticated/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthenticatedAuthOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuthOnboardingRoute: typeof AuthenticatedAuthOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthOnboardingRoute: AuthenticatedAuthOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
