/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordCodeRouteImport } from './routes/auth/reset-password-code'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRequestResetPasswordRouteImport } from './routes/auth/request-reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCreateAccountRouteImport } from './routes/auth/create-account'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedTicketsCreateRouteImport } from './routes/_authenticated/tickets/create'
import { Route as AuthenticatedAuthOnboardingRouteImport } from './routes/_authenticated/auth/onboarding'
import { Route as AuthenticatedTicketsTicketIdIndexRouteImport } from './routes/_authenticated/tickets/$ticketId/index'
import { Route as AuthenticatedTicketsTicketIdEditRouteImport } from './routes/_authenticated/tickets/$ticketId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordCodeRoute = AuthResetPasswordCodeRouteImport.update({
  id: '/auth/reset-password-code',
  path: '/auth/reset-password-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRequestResetPasswordRoute =
  AuthRequestResetPasswordRouteImport.update({
    id: '/auth/request-reset-password',
    path: '/auth/request-reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateAccountRoute = AuthCreateAccountRouteImport.update({
  id: '/auth/create-account',
  path: '/auth/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsCreateRoute =
  AuthenticatedTicketsCreateRouteImport.update({
    id: '/tickets/create',
    path: '/tickets/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthOnboardingRoute =
  AuthenticatedAuthOnboardingRouteImport.update({
    id: '/auth/onboarding',
    path: '/auth/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsTicketIdIndexRoute =
  AuthenticatedTicketsTicketIdIndexRouteImport.update({
    id: '/tickets/$ticketId/',
    path: '/tickets/$ticketId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsTicketIdEditRoute =
  AuthenticatedTicketsTicketIdEditRouteImport.update({
    id: '/tickets/$ticketId/edit',
    path: '/tickets/$ticketId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-code': typeof AuthResetPasswordCodeRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
  '/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-code': typeof AuthResetPasswordCodeRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
  '/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/create-account': typeof AuthCreateAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-code': typeof AuthResetPasswordCodeRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/auth/onboarding': typeof AuthenticatedAuthOnboardingRoute
  '/_authenticated/tickets/create': typeof AuthenticatedTicketsCreateRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/tickets/$ticketId/edit': typeof AuthenticatedTicketsTicketIdEditRoute
  '/_authenticated/tickets/$ticketId/': typeof AuthenticatedTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/$'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/request-reset-password'
    | '/auth/reset-password'
    | '/auth/reset-password-code'
    | '/auth/verify-email'
    | '/'
    | '/auth/onboarding'
    | '/tickets/create'
    | '/tickets'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/request-reset-password'
    | '/auth/reset-password'
    | '/auth/reset-password-code'
    | '/auth/verify-email'
    | '/'
    | '/auth/onboarding'
    | '/tickets/create'
    | '/tickets'
    | '/tickets/$ticketId/edit'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/api/$'
    | '/auth/create-account'
    | '/auth/login'
    | '/auth/request-reset-password'
    | '/auth/reset-password'
    | '/auth/reset-password-code'
    | '/auth/verify-email'
    | '/_authenticated/'
    | '/_authenticated/auth/onboarding'
    | '/_authenticated/tickets/create'
    | '/_authenticated/tickets/'
    | '/_authenticated/tickets/$ticketId/edit'
    | '/_authenticated/tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCreateAccountRoute: typeof AuthCreateAccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRequestResetPasswordRoute: typeof AuthRequestResetPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetPasswordCodeRoute: typeof AuthResetPasswordCodeRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password-code': {
      id: '/auth/reset-password-code'
      path: '/auth/reset-password-code'
      fullPath: '/auth/reset-password-code'
      preLoaderRoute: typeof AuthResetPasswordCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/request-reset-password': {
      id: '/auth/request-reset-password'
      path: '/auth/request-reset-password'
      fullPath: '/auth/request-reset-password'
      preLoaderRoute: typeof AuthRequestResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-account': {
      id: '/auth/create-account'
      path: '/auth/create-account'
      fullPath: '/auth/create-account'
      preLoaderRoute: typeof AuthCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/create': {
      id: '/_authenticated/tickets/create'
      path: '/tickets/create'
      fullPath: '/tickets/create'
      preLoaderRoute: typeof AuthenticatedTicketsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auth/onboarding': {
      id: '/_authenticated/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthenticatedAuthOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId/': {
      id: '/_authenticated/tickets/$ticketId/'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/$ticketId/edit': {
      id: '/_authenticated/tickets/$ticketId/edit'
      path: '/tickets/$ticketId/edit'
      fullPath: '/tickets/$ticketId/edit'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuthOnboardingRoute: typeof AuthenticatedAuthOnboardingRoute
  AuthenticatedTicketsCreateRoute: typeof AuthenticatedTicketsCreateRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedTicketsTicketIdEditRoute: typeof AuthenticatedTicketsTicketIdEditRoute
  AuthenticatedTicketsTicketIdIndexRoute: typeof AuthenticatedTicketsTicketIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuthOnboardingRoute: AuthenticatedAuthOnboardingRoute,
  AuthenticatedTicketsCreateRoute: AuthenticatedTicketsCreateRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedTicketsTicketIdEditRoute: AuthenticatedTicketsTicketIdEditRoute,
  AuthenticatedTicketsTicketIdIndexRoute:
    AuthenticatedTicketsTicketIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  AuthCreateAccountRoute: AuthCreateAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRequestResetPasswordRoute: AuthRequestResetPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetPasswordCodeRoute: AuthResetPasswordCodeRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
